parent(ritu,mita).
parent(ritu,sonia).
parent(suman,mita).
parent(suman,pradip).
parent(pradip,amita).
parent(mita,amita).
parent(amita,joy).
parent(amita,dipti).
parent(rajib,sudip).
parent(dipti,sudip).
male(suman).
male(pradip).
male(rajib).
male(joy).
male(sudip).
female(ritu).
female(mita).
female(sonia).
female(amita).
female(dipti).
grandparent(X,Y):-parent(X,Z),parent(Z,Y).
sister(X,Y):-parent(Z,X),parent(Z,Y),female(X),not(X=Y).
